<?php
/*************************************************************************
 Copyright 2011 Vevui Development Team

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*************************************************************************/

class L10n extends Lib
{
	function  __construct()
	{
		parent::__construct();
	}

	private function _get_locales($locale)
	{
		if (NULL === $locale) $locale = $this->l->client->langs;
		if (NULL === $locale) $locale = $this->e->l10n->default;
		if (!is_array($locale)) $locale = array($locale);
		return $locale;
	}

	private function _get_cached_locale($cache_file_dir, $filename)
	{
		$cache_file_path = $cache_file_dir.'/'.$filename.'.php';

		$xml_ttl = $this->e->l10n->xml_ttl;

		$this->disable_errors();
		@include($cache_file_path);
		$this->enable_errors();

		if ( (!isset($data)) || (VEVUI_VERSION != $data['_vevui']['version']) )
		{
			unset($data);
			return NULL;
		}

		// Skip checking for modifications.
		if ($xml_ttl && ($data['_vevui']['timestamp']+$xml_ttl) < time())
		{
			$cldr_base_path = $this->e->l10n->cldr_path.'/common/main';

			foreach($data['_vevui']['locales'] as $lang)
			{
				// The file was modified.
				$mtime = @filemtime($cldr_base_path.'/'.$lang.'.xml');
				if ( (FALSE === $mtime) || ($data['_vevui']['timestamp'] < $mtime) )
				{
					unset($data);
					return NULL;
				}
			}

			// Unmodified, update timestamp on file to prevent checking until new TTL comes.
			$data['_vevui']['timestamp'] = time();

			// Save file atomically. If not possible, we still work but very slow!
			$tempname = tempnam($cache_file_dir, '_'.$filename.'.php.'.microtime(TRUE));

			$content = '<?php $data = unserialize(\''.str_replace('\'', '\\\'', serialize($data))."');\n".'// Generated by Vevui '.VEVUI_VERSION.' on '.date('c');
			$this->disable_errors();
			@file_put_contents($tempname, $content);
			@rename($tempname, $cache_file_path);
			$this->enable_errors();
		}

		return $data;
	}

	function countries($locale = NULL, $merge_with_default = TRUE, $short_names = FALSE)
	{
		$cldr_base_path = $this->e->l10n->cldr_path.'/common/main';
		$cache_file_dir = $this->e->l10n->cache_path.'/countries';
		foreach($this->_get_locales($locale) as $l)
		{
			$l = str_replace('-', '_', $l);
			$filename = strtolower($l).($merge_with_default?'_def':'').($short_names?'_short':'');
			$data = $this->_get_cached_locale($cache_file_dir, $filename);
			if (NULL !== $data)
			{
				unset($data['_vevui']);
				return $data;
			}

			// Regenerate file.
			$parts = explode('_', $l);
			$count = count($parts);

			$langs = array();
			$files = array();
			$tmp = array();
			if ($merge_with_default) $langs[] = $this->e->l10n->default;
			for($i=0; $i<$count; ++$i)
			{
				$tmp[] = $parts[$i];
				$lc = implode('_', $tmp);
				$langs[] = $lc;
				array_unshift($files, $lc);
			}

			// See if one of the parents exists and is returnable.
			foreach($files as $l)
			{
				if (is_file($cldr_base_path.'/'.$l.'.xml'))
				{
					$data = $this->_get_cached_locale($cache_file_dir, $tmp);
					if (NULL !== $data)
					{
						unset($data['_vevui']);
						return $data;
					}
				}
			}

			$countries = array();
			foreach($langs as $l)
			{
				$this->disable_errors();
				$xml = @simplexml_load_file($cldr_base_path.'/'.$l.'.xml');
				$this->enable_errors();
				if (FALSE === $xml) continue;

				$filename = strtolower($l).($merge_with_default?'_def':'');

				$tmp = $xml->localeDisplayNames;
				if (NULL === $tmp) continue;

				$tmp = $tmp->territories;
				if (NULL === $tmp) continue;

				foreach($tmp->children() as $territory)
				{
					$type = (string) $territory['type'];
					if (ctype_upper($type))
					{
						if ( (!array_key_exists($type, $countries)) || (NULL===$territory['alt']) || ($short_names && ('short'==(string)$territory['alt'])) )
						{
							$countries[$type] = (string) $territory;
						}
					}
				}
			}

			if (!$countries) continue;

			$data = $countries;
			$data['_vevui'] = array();
			$data['_vevui']['version'] = VEVUI_VERSION;
			$data['_vevui']['timestamp'] = time();
			$data['_vevui']['locales'] = $langs;

			// Save file atomically. If not possible, we still work but very slow!
			$this->disable_errors();
			if(!is_dir($cache_file_dir))
			{
				@mkdir($cache_file_dir, 0700, TRUE);
			}

			$tempname = tempnam($cache_file_dir, '_'.$filename.'.php.'.microtime(TRUE));

			$content = '<?php $data = unserialize(\''.str_replace('\'', '\\\'', serialize($data))."');\n".'// Generated by Vevui '.VEVUI_VERSION.' on '.date('c');
			@file_put_contents($tempname, $content);
			@rename($tempname, $cache_file_dir.'/'.$filename.'.php');
			$this->enable_errors();

			return $countries;
		}

		return NULL;
	}

	function languages($locale = NULL, $merge_with_default = TRUE)
	{
		$cldr_base_path = $this->e->l10n->cldr_path.'/common/main';
		$cache_file_dir = $this->e->l10n->cache_path.'/languages';
		foreach($this->_get_locales($locale) as $l)
		{
			$l = str_replace('-', '_', $l);
			$filename = strtolower($l).($merge_with_default?'_def':'');
			$data = $this->_get_cached_locale($cache_file_dir, $filename);
			if (NULL !== $data)
			{
				unset($data['_vevui']);
				return $data;
			}

			// Regenerate file.
			$parts = explode('_', $l);
			$count = count($parts);

			$langs = array();
			$files = array();
			$tmp = array();
			if ($merge_with_default) $langs[] = $this->e->l10n->default;
			for($i=0; $i<$count; ++$i)
			{
				$tmp[] = $parts[$i];
				$lc = implode('_', $tmp);
				$langs[] = $lc;
				array_unshift($files, $lc);
			}

			// See if one of the parents exists and is returnable.
			foreach($files as $l)
			{
				if (is_file($cldr_base_path.'/'.$l.'.xml'))
				{
					$data = $this->_get_cached_locale($cache_file_dir, $tmp);
					if (NULL !== $data)
					{
						unset($data['_vevui']);
						return $data;
					}
				}
			}

			$first = TRUE;
			$languages = array();
			foreach($langs as $l)
			{
				$this->disable_errors();
				$xml = @simplexml_load_file($cldr_base_path.'/'.$l.'.xml');
				$this->enable_errors();
				if (FALSE === $xml) continue;

				$filename = strtolower($l).($merge_with_default?'_def':'');

				$tmp = $xml->localeDisplayNames;
				if (NULL === $tmp) continue;

				$tmp = $tmp->languages;
				if (NULL === $tmp) continue;

				foreach($tmp->children() as $lang)
				{
					$type = (string) $lang['type'];
					$languages[$type] = (string) $lang;
				}
			}

			if (!$languages) continue;

			$data = $languages;
			$data['_vevui'] = array();
			$data['_vevui']['version'] = VEVUI_VERSION;
			$data['_vevui']['timestamp'] = time();
			$data['_vevui']['locales'] = $langs;

			// Save file atomically. If not possible, we still work but very slow!
			$this->disable_errors();
			if(!is_dir($cache_file_dir))
			{
				@mkdir($cache_file_dir, 0700, TRUE);
			}

			$tempname = tempnam($cache_file_dir, '_'.$filename.'.php.'.microtime(TRUE));

			$content = '<?php $data = unserialize(\''.str_replace('\'', '\\\'', serialize($data))."');\n".'// Generated by Vevui '.VEVUI_VERSION.' on '.date('c');
			@file_put_contents($tempname, $content);
			@rename($tempname, $cache_file_dir.'/'.$filename.'.php');
			$this->enable_errors();

			return $languages;
		}

		return NULL;
	}
}

/* End of file sys/libraries/l10n.php */
