<?php
/*************************************************************************
 Copyright 2011 Vevui Development Team

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*************************************************************************/

class ConfigLoader
{
	function __construct()
	{
		$config_dir = APP_PATH.'/e';
		$config_file_path = ROOT_PATH.'/cache/config.php';

		$core = & Vevui::get();
		$core->disable_errors();
		@include($config_file_path);
		$core->enable_errors();

		if (isset($config) && VEVUI_VERSION == $config->_vevui->version)
		{
			$config_ok = TRUE;
		}
		else
		{
			$config_ok = FALSE;
			$config = new stdClass();
		}

		// Skip checking for modifications.
		if ( (!$config_ok) || ($config->app->config_ttl && ($config->_vevui->timestamp+$config->app->config_ttl) < time()) )
		{
			$config_mtime = $config_ok?$config->_vevui->timestamp:FALSE;

			$files = @scandir($config_dir);
			$modified = FALSE;
			$yaml_files = array();
			foreach($files as $file)
			{
				if (0!==strcasecmp(substr($file, -5), '.yaml')) continue;
				$name = strtolower(substr($file, 0, -5));
				$yaml_files[$name] = TRUE;

				if ( (FALSE === $config_mtime) || ($config_mtime < @filemtime($config_dir.'/'.$file)) || (!array_key_exists($name, $config)) )
				{
					$config->{$name} = $core->l->yaml->load($config_dir.'/'.$file, 'haanga' != $name);
				}
			}

			// Delete old entries that no longer exist as files.
			foreach ($config as $key => $value)
			{
				if ( ('_vevui' != $key) && (!array_key_exists($key, $yaml_files)) )
				{
					unset($config->{$key});
				}
			}

			$config->_vevui = new stdClass();
			$config->_vevui->version = VEVUI_VERSION;
			$config->_vevui->timestamp = time();

			// Save config atomically. If not possible, we still work but very slow!
			$tempname = tempnam($config_dir, '_config.php.'.microtime(TRUE));

			$content = '<?php $config = unserialize(\''.str_replace('\'', '\\\'', serialize($config))."');\n".'// Generated by Vevui '.VEVUI_VERSION.' on '.date('c');
			$core->disable_errors();
			@file_put_contents($tempname, $content);
			@rename($tempname, $config_file_path);
			@unlink($tempname);
			$core->enable_errors();
		}

		// Assign config to local fields.
		foreach ($config as $key => $value)
		{
			$this->{$key} = $value;
		}
	}
}

/* End of file sys/core/configloader.php */
